services:
  - docker

before_install:
  - docker-compose -f docker-compose-storage.yml -d up
  - docker-compose -f docker-compose-storage.yml run --rm api-deployer /setup.sh

script:
  - docker --version
  - docker ps